project:
  type: website
  output-dir: docs

website:
  title: "RPAD 507 - Integrative Capstone"
  navbar:
    background: secondary
    left:
      - text: "About"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus507.qmd
      - text: "Assignments"
        file: assignments.qmd
      - text: "Stratton County"
        file: stratton.qmd

  sidebar: 
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - individual.qmd
        - stratton.qmd
        - group.qmd
        
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

