---
title: "Stratton County"
---

## Introduction

Stratton County's current population totals 325,000 people and includes two major population centers, the City of Stratford (population 65,000) and the City of Ogden Mills (population 120,000). Stratford, the county seat, founded in 1731, is a flourishing historic city. Ogden Mills, founded in 1875, is a blighted and aging 19th century industrial mill town, the former home of the Ogden Works (abandoned in 1971). The two population centers are separated by the suburban towns of East Ogden and West Stratford, along the scenic Stratton River Valley. The county has five other surrounding towns that are more rural in character. Stratton County is governed by an elected County Executive and a 16-member County Legislature (representing 16 proportional legislative districts). The current County Executive was first elected to a four-year term in 2018.

Today is January 25th, 2023. The County Executive is developing a plan to reduce the County's operating budget in the coming fiscal year (which begins September 1st) and has directed all County departments and agencies to submit plans for the 2023 budget which will **cut departmental operating budgets by 10% from current (2022) authorized levels**, while absorbing any contractually-mandated increases and maintaining county revenues. The County Executive is required by law to submit the Executive Budget proposal to the County Legislature for its consideration by August 15th.

In addition to calling for plans to reduce departmental operating budgets by 10% in the upcoming year, the County Executive's January 15th directive to all department heads highlighted the following:

-   "We face significant fiscal pressure due to rising health care and pension costs, continued erosion of private sector jobs, and increasing human service and related needs"; and
-   "As agencies develop plans to cut budgets by 10%, all are directed to balance three specific goals for the coming year:
    -   Keep costs down,
    -   Lower taxes, and
    -   Strategically invest in the future of Stratton County."

Over the past two weeks, excerpts of this directive have been published in the local media and on the county website, generating considerable commentary in print, on-line and among elected officials, community activists, and the public.

The Stratton County Parks Department began its internal budget development process (for 2023) in early August. This included a series of internal meetings with park superintendents and key staff and an internal assessment of needs and issues facing the department in the coming year. Additional in-house (department-level) meetings have been held following the January 15th directive.

## Background Information on Stratton County Parks

The Stratton County Parks Department is a cabinet-level unit of county government, with the Director of Parks (you) reporting directly to the County Executive. The county has five major parks and hosts 450,000 visitors annually. The agency's current budget totals \$2.70 million including 20 year-round (annual) staff positions, supplemented with part-time and temporary (hourly) staff on a seasonal basis.

In 2020, Stratton County received a state "2025 Vision" grant to update its parks and recreation and community development plans. A consulting firm was engaged to assist in the development of the plan, a community-based advisory board was established, and 15 public stakeholder meetings were held at various locations in the county over the ensuing year. In October 2021, the final plan was completed and accepted by the then County Executive (who has since left office). The parks portion of the plan identified five policy priorities for Stratton County Parks:

1.  Access to All: "Parks are community assets and support social equity and inclusion. Parks and park programs should be available, affordable and accessible to all county residents, regardless of age, ability, or economic status."
2.  Health and Wellness: "Parks provide opportunities for active and passive recreation and promote community health, mental health and the well-being of county residents."
3.  Conservation: "Parks preserve and protect important natural, cultural and historic resources, which are held in trust for future generations."
4.  Community Development: "Parks promote the well-being of communities, supporting education, economic development, and the growth and revitalization of communities."
5.  Progress and Prosperity: "Parks are important community-owned assets which should be leveraged to promote community growth and economic progress, job creation, and community identity and prosperity."

Originally established under the grant guidelines, the Parks Community Advisory Board (PCAB) was formalized in 2021. Current members of the PCAB include the husband of the mayor of Ogden Mills (who is also a partner in a downtown Stratford law firm), the CEO of the Consolidated Boys and Girls Clubs of Stratton County, the President of the Stratton Valley Hiking Club, the outdoor editor of the local newspaper the Stratford Herald, the vice-chair of the Stratford-Ogden Youth Soccer Association, and a "user representative" from each of the County's five major parks. The grant also requires that the PCAB meet at least annually (last year's meeting was held in mid-November) and that the County submit a five-year progress report to the state (which is due by October 31st, 2023).

The Stratton County Park system has five major parks (see [map](map.pdf)).

### Ogden Falls County Park

#### Background

Ogden Falls is the county's newest county park, opening in 1980. It is located in the Stratton Shores neighborhood in the city of Ogden Mills on the site of an abandoned amusement park and adjacent to the former Ogden Works industrial lands (located at the site of the historic water wheel that powered the mills in the 19th century). The park's original development was part of a multi-million dollar federal-state-local "Community Revitalization" project, creating a new public park (including a large public swimming pool, skating rink, running track, tennis and basketball courts, play areas and athletic fields, and waterfront esplanade), redevelopment of the adjacent former mill buildings into a retail complex, the development of affordable housing, and new streets, landscaping, and sidewalks. Now, over 40 years later, the park is showing its age from overuse and lack of ongoing maintenance. Play areas, the swimming pool (and associated mechanical systems), athletic fields, and bathrooms are all in dire need of rehabilitation. Over the last decade, the neighborhood surrounding the park has declined, as well; the retail shops are nearly empty and the area has one of the highest crime rates and students in the neighborhood exhibit the lowest high school graduation rates in the county. Recent press stories describing gang activities taking place in the surrounding neighborhood are leading many residents to feel the park may be unsafe. Despite all of that, community residents rely on the park for green space. Its picnic and lawn areas, playground and basketball courts are in almost constant use and neighborhood children look forward to the pool's opening each summer. Even with its many challenges, the park remains the heart of the community. The newly re-elected (in 2021) Mayor of Ogden Mills campaigned on a theme of revitalizing the city and redeveloping the Stratton Shores neighborhood adjacent to the park. The current Mayor formerly was the City Council member representing the Stratton Shores neighborhood, and the revitalization is high on her to-do list.

#### Current Issues

The Assistant Park Superintendent position for Ogden Falls is currently vacant as the incumbent has been temporarily reassigned to the Stratton Valley Golf Course (note: the position is budgeted for in the current year, even though it is not filled). As the park is currently entering its "off season" (with the start of the new school year), the temporary loss of this essential position is not critical---but the position should be refilled before next spring. As part of the agency's internal 2023 budget development process, the park's Superintendent also has requested the addition of a full-time Ranger (\$50,000 for salary and benefits) in the coming year to provide security at the park in the evening hours, year round, as the ability of the County Sheriff's patrols to provide coverage is limited. Another concern is that permits for the best usage times for the tennis courts, skating rink and the athletic fields have been awarded to various organizations (both nonprofits and various business-oriented leagues) for use by their members and clients -- at the exclusion of "drop-in" use by neighborhood residents. Reversing this policy and providing more "open community time" would be desirable, but would both cost the county approximately \$25,000 in permit revenue, and require \$20,000 in increased seasonal staffing for supervision and \$10,000 in associated materials costs. In addition, this past July the state Labor Department (in response to anonymous employee complaints) has recently conducted a safety inspection of the park and has identified numerous violations, including the unsafe storage and inadequate ventilation of hazardous chemicals, improper workplace practices and deficient employee safety training; remedying the hazardous materials storage violations alone will cost the park \$25,000 in the upcoming year.

### Bonavista Reserve

#### Background

The Bonavista Reserve is located on the site of the former Winthrop Arlington Ogden estate, in a rural area of Stratton County. The land was given to the county for use as "a public playground and natural reserve in perpetuity" by the Ogden family in 1921. The park has panoramic views of the Stratton River Valley, extensive nature and hiking trails, ornamental gardens, numerous natural ponds, and wetlands. A small nature center and museum was opened in 2011 after an extensive private fundraising effort, led by the park's nonprofit Friends of Bonavista Reserve. The park is a favorite for school groups and has an award-winning nature trail.

#### Current Issues

Newly-adopted state educational standards require that all 3rd and 4th grade science students receive hands-on (field) environmental education instruction as part of their science curriculum. This change has significantly impacted operations at the Reserve. School group bookings have doubled in the past year and, at times, the small nature center has been filled beyond capacity with teachers and students. There aren't enough trained environmental educators on staff (an additional \$20,000 in seasonal staffing would be needed to meet current demand), the nature center's exhibits and collections of "hands-on" materials should be replaced (which will cost \$25,000). Also, the Reserve's museum and network of nature trails need to be upgraded to be able to meet new accessibility standards in order to properly serve disabled students. Without these upgrades, school groups may stop coming to the park. The cost to upgrade the accessibility of the nature trails and museum is estimated at \$50,000. The President of the Friends of Bonavista Reserve has conducted extensive research into potential funding opportunities and has identified a proposed new competitive federal grant program called "Get Kids Outside"; that program is not funded in the current federal budget and, at best, funds will not be available for at least 18 to 24 months. The Friends of Bonavista Reserve is organizing a petition drive and has scheduled a park tour by the local Congressional representative in the coming weeks. There has been discussion about including this in the Capital Budget discussion for next year (which occurs at a different time), but some are worried that delaying accessibility improvements will cause students to stop attending the park before a capital project would begin.

### Stratton Valley Golf Course

#### Background

The original members of the Stratton Valley Country Club (SVCC), located in West Stratford, were the "executive class" of the Ogden Works and related businesses when the industrial age was booming in Stratton County. As industry declined, so did SVCC and it was converted into a privately-owned "daily play" course in the 1970s. The county purchased it and opened it as a public golf course in 1977. The Stratton Valley Golf Course is county-operated, with county employees providing for operations and maintenance. A private concessionaire (StratLinks, LLC, a locally-owned business) operates the pro shop and the clubhouse restaurant under a contractual (ten year) lease, under parkland alienation legislation, paying a commission to the County of 15% of all income received from restaurant and pro shop sales, lessons, and related services. This contract expires December 31st, 2022. Five years ago, the Stratton Business Association campaigned to have all golf course operations fully privatized and three years ago the county chose to incrementally privatize revenue collection operations (only) at the course by expanding and amending the StratLinks agreement. Under that amended agreement, StratLinks is paid a \$25,000 service fee annually to collect greens fees at the course and all revenues collected are deposited daily directly into County accounts. Since becoming a county park, Stratton Valley consistently has been ranked as one of the top 25 "most affordable" public golf courses in the state. Greens fees were raised in 1985, 1999 and again in 2007.

#### Current Issues

Last year the course experienced a significant public scandal when a state audit revealed that the course Superintendent (a county employee) received gifts, free meals, and other benefits from a local golf equipment shop owner (a former business partner of the current StratLinks owner) who was allowed to use the public course for clinics, equipment demonstrations, and private outings, without going through the normal permit and bidding process. The audit also found (but could not explain) that revenue collections from green fees at the course declined from \$425,000 in 2020 to \$400,000 last year. Following the release of the audit last spring, the Superintendent retired and has been temporarily replaced by reassignment of the former Assistant Superintendent at Ogden Falls. The existing Assistant Superintendent at Stratton Valley remains as the park's #2, but is under an ongoing "cloud of suspicion" from the scandal. He has let it be known (unofficially) that if he is not promoted to a Superintendent's position, he also will retire early next year. The audit and resulting scandal have brought renewed calls by some to fully privatize the course in order to "clear up this mess." In addition to filling the Superintendent's position (with either candidate), the golf course is in need of additional mowing equipment to replace a 15-year old tractor mower. Since this is specific to the golf course and is not a capital improvement, you have been told it needs to be in the operating budget and not the capital budget (if included at all). A new \$50,000 mower would reduce mowing time by 25% (saving an estimated \$25,000 in staff time) and would reduce equipment repair costs by \$15,000 annually (starting in 2022).

### Twin Lakes County Park

#### Background

Twin Lakes County Park, located in East Ogden, is the county's most popular park, with two lakes, a large swimming beach and bathhouse complex, five reservable picnic pavilions, picnic areas, boat rentals, and a soccer field complex. Twin Lakes caters to a largely suburban audience, being located outside the service area of the County's public-transportation system reachable only by car. The park was recognized in 2018 as a "Gold Medal" park by the National Recreation and Park Association, in part due to the County's investment in the community soccer program. Park staff are currently implementing a five-year plan to achieve "platinum" recognition in 2023, which would make it the first "Platinum Medal" county park in the state.

#### Current Issues

Twin Lakes is regarded as Stratton County's "backyard park" as it is located in the most suburban part of the county. The school boards, administrators, and athletic departments from both West Stratford and East Ogden school districts have approached the park's superintendent with a plan to develop an annual "Family Fun and Fitness Festival" to encourage exercise, outdoor activities and combat childhood obesity. This group also has approached members of the Parks Community Advisory Board in support of funding for the festival in next year's budget. The Festival would be held in mid-September to coincide with the opening of school. For the park, events that communicate the message that "outdoor activity doesn't stop after Labor Day" would also help to boost park visitation in the fall and winter months. The two-day event would include a 5K race and fun run, instruction in kayaking, a bike rodeo, a three-on-three youth basketball tournament, and other activities. Additional staff would need to be brought on for the weekend, recreational equipment and supplies would need to be purchased, portable toilets would have to be rented, and contracts would need to be let for activity leaders, instructors, and referees---at a total cost of \$27,500.

### Stratford Green and Courthouse Square Parks

#### Background

Stratford Green is a large, Victorian-era urban park located in the heart of the City of Stratford, with 78 acres of lawns and ornamental plantings, fountains, a band shell and a small lake. Five years ago, as part of a "government efficiency initiative" by the then County Executive, jurisdiction of Stratford Green was transferred from the City of Stratford to Stratton County. Management of Stratford Green was combined with the smaller (5 acre), adjacent county-owned and operated Courthouse Square Park. This transfer has substantially benefitted city taxpayers and business-owners in the forms of reduced operating costs and taxes. Security at the two-park complex has been an area of conflict between the City of Stratford (which had been responsible for Stratford Green) and the County Sheriff (which has always been responsible for Courthouse Square), especially when there are large public events requiring additional police presence. The current County Executive, elected to a four-year term in 2018, opposed the transfer of the park from the city to the county as a member of the County Legislature representing suburban East Ogden.

#### Current Issues

The most beloved features of Courthouse Square Park are the "Union Oaks", two trees planted in 1875 to commemorate the end of the Civil War. The trees are planted about 100 feet apart and the area between them is currently a brick-paved courtyard, a popular place for community gatherings (and for county office building and courthouse employees to eat lunch!). The 140+ year-old trees are failing from neglect; last winter a large limb fell following an ice storm, damaging the courtyard's ornamental fountain. A recent private study commissioned by a concerned citizens group, The Campaign to Save the Union Oaks, has recommended that the county contract with a certified professional arborist to "save the trees" and to remove the paved-over courtyard and replace it with a lawn and gardens. The cost of an arborist on-contract will cost an additional \$50,000 annually (for at least 3-5 years) and the estimated cost to remove and relocate the courtyard and create a new garden area is \$350,000. This would be funded from county Capital Improvement funds or funds that will have to be raised largely from grants or from private or other sources (or some combination). The Stratford Herald, the regional daily newspaper, has recently editorialized in favor of the campaign to save the Union Oaks, calling the potential loss of the historic trees, if it happens, "a potent symbol of government incompetence and neglect." In addition, the County Sheriff already has notified the Parks Department that it plans to reduce security patrols at Stratford Green and Courthouse Square in 2022 as part of its 10% reduction plan; this action, if approved, would save the Sheriff's department \$50,000 annually (and would cost the Parks department a like amount simply to maintain park security at current levels).

## Parks Department Administration

#### Background

In addition to the 15 annual-salaried staff (one of which is currently vacant) authorized in the current (2022) budget and 50 temporary hourly staff hired on a seasonal basis working in the parks, the Stratton County Parks Department has a central administrative staff of five people, consisting of a Director, an Assistant Director, a Business Manager, and two clerical support staff. Previously, the Department's central office also had a Special Programs Coordinator, who was responsible for staff training, coordination of volunteers, intergovernmental relations, grant-writing and working with community and affiliated organizations. That person retired 18 months ago and the position has not been filled, nor has the Director requested re-filling this position.

#### Current Issues

The retired former Special Programs Coordinator has continued to provide critical staff training on a part-time basis, as well as grants-related research, at a part-time salary of \$25,000 annually, including benefits. Training includes mandatory sexual harassment prevention, mandatory workplace health and safety for all annual and seasonal employees on an annual basis, as well as job-related customer service and job skills training for all staff. Last month, a taxpayer group published in a blog a list of retired county employees receiving a public pension who had returned to salaried positions (so called "double-dippers"), including this individual. In reaction, the County Executive directed that all such arrangements be discontinued as of next January 1 (2023). Replacing this position with a private contractor is estimated to cost \$35,000 next year.

## Additional Budget Information

#### Current and Requested Budgets

The current fiscal year annual operating budget for the Parks Department totals \$2,704,000. Therefore, the budget plan to be submitted for next year cannot exceed \$2,433,600, reflecting a 10% reduction from the current level. The current annual operating budget, current staffing, and requested budget amounts for each park are summarized in the spreadsheet posted on Blackboard along with background data on revenue collection from user fees and contract payments and visitor profiles for each park.

Under the current county budget, all earned revenues collected in the parks are transferred to the General Operating Fund and are not earmarked specifically for Park use; rather, they become part of a large pool of funds that is subject to the normal County budgeting process. The General Operating Fund is used by the County to fund all of its operations, not just the Parks, and you must at least maintain current levels. Any proceeds from grants or from nonprofit and private fundraising are kept in the Parks Department and may be used to offset up to 2% of the cuts; in other words, if you can reasonably raise \$54,080 from philanthropy, you can reduce the budget to not more than \$2,487,680 (but be sure to mention in the report and presentation how this benefits the county.) Grants and donations can only be used for specific projects and are not available for general operating support.

#### Capital Improvement Plan

Stratton County also has a centralized Capital Budget, which is managed by the county's Engineering Services Division of the Department of Public Works. The Consolidated County Capital Budget funds longer-term investments in building and facilities, land, infrastructure and fixed equipment for county government. The Consolidated County Capital Budget includes allocations for projects on behalf of the various county departments. Capital funds are not included in departmental budgets. Stratton County follows a rolling capital planning process. Each March, specific capital projects are identified by each department for possible inclusion in the County Budget for the following year. These are placed on a "pre-approved" planning list. This step allows potential projects to undergo planning, engineering and other reviews before they are formally authorized in the annual budget (for the fiscal year beginning in January). The total cost of projects included on this preliminary "planning list" typically exceeds the funding amounts anticipated for the upcoming year in order to provide flexibility. Based on funding available and capital investment priorities, any of these "pre-approved" projects that are not funded in the subsequent year's budget go back into the queue for the following year.

Each item on the "pre-approved" Planning List represents a specific priority capital project that has undergone some degree of preliminary engineering design and cost estimation. The capital allocation in the current (2022) budget for the Parks Department totals \$500,000. As it is August, these projects are already underway. The current, preliminary "pre-approved" 2023 planning list for Parks, developed last March, stands at \$750,000, and is summarized by park below:

|                                | Current Budget (2022 Approved) | Planning List (2023 Pre-Approved) |
|:----------------------|:----------------------|--------------------------:|
| Ogden Falls                    | \$150,000                      |                         \$375,000 |
| Bonavista Reserve              | \$150,000                      |                          \$50,000 |
| Stratton Valley GC             | \$50,000                       |                          \$75,000 |
| Twin Lakes                     | \$100,000                      |                         \$200,000 |
| Stratford Green/Courthouse Sq. | \$50,000                       |                          \$50,000 |

Please note that the above Planning List amounts by park projects reflect specific project needs identified more than six months ago and do not reflect "current issues" identified in the Parks Department's 2023 budget development process. It is expected that the level of capital funding for 2024 will be consistent with the current budget but the specific projects to be funded for 2024 have not yet been finalized. As capital improvement funds are not part of the Parks Department's operating budget, any proposed reductions in capital spending for Parks may not be used to offset required cuts to the Department's operating budget in the coming year. However, in principle, requests for funding for larger, long-term capital improvement projects can be made through the Capital Improvement Plan, though with a large degree of uncertainty and longer timeline.

## Collective Bargaining Agreements

All Parks employees are represented by public employee unions (except for the Director of Parks). Union contracts currently in force on a county-wide basis include the following provisions:

1.  2.5% salary increases in the form of cost-of-living salary adjustments (COLAs) for all employees (and positions), annual and seasonal, effective January 1, 2023.
2.  No layoffs of existing annual staff due until expiration of the current collective bargaining agreement on December 31st 2023. Annual-salaried employees (and their positions) may be eliminated (laid off) only as a result of the closure of facilities and elimination of programs, which must be specified as part of the adopted budget.
3.  County employees covered by collective bargaining may be transferred between physical work locations (facilities or departments) on an involuntary basis only upon 90 days' notice and posting of a "notice of transfer" list which seeks to identify employees wishing to transfer on a voluntary basis. If two or more employees request a transfer of location, the determination of which employee to transfer must be made on the basis of seniority (defined as the length of county employment). Employees may be temporarily reassigned involuntarily only up to 90 days, in order to meet emergency and other program and workload priorities. This may be extended by management up to an additional 90 days.
4.  Seasonal employees of the Parks Department are considered to be temporary and, technically, are terminated and rehired from year-to-year. Their employment is not guaranteed from year-to-year, and they are not restricted to a particular park location within that year. This is why the distribution of their hours across parks was even for the current budget (including Stratton Valley, whose budget includes an additional \$25,000 for the StratLinks contract.)
5.  Unilateral layoffs of staff or reductions in salary and benefits are not permitted under the County-wide collective bargaining process with employee unions. Recent court cases strictly prohibit the County or any of its departments from unilaterally altering the terms of existing union contracts.

## Additional Details
You can find additional budget and demographics details about Stratton County [here](stratton-data.xlsx).