---
title: "Syllabus"
---

# Integrative Capstone

## RPAD 507

👨‍🏫: Stephen Holt, Ph.D.\
📆: Asynchronous Online with Synchronous Check-Ins\
📧: sbholt\@albany.edu\
🏫: Tuesdays and Thursdays from 2:00 pm to 5:00 pm or by appointment - book [here](https://outlook.office.com/bookwithme/user/ebafd191395240ce81ec760aa540214b@albany.edu?anonymous&ep=plink); in-person in Milne 324 or online in [GatherTown](https://app.gather.town/app/REBbcSYb3BTtxRhY/ussalbany).[^1]\
☎️: 518-442-3309

[^1]: Password is RockCollege. Feel free to also use as a meeting spot with your groups - the rooms are private meeting rooms (this will make sense when you use it) and the space itself has a 25 person capacity.

## Course Description

## Class Policies

-   Public policy is a professional field; therefore, I emphasize professional skills in the classroom and assignments. Professional skills are punctuality, adhering to deadlines, and preparedness.
-   After the first week, readings for each week should be completed by the Tuesday of that week (that is, BEFORE CLASS!). While much of the class reading comes from the text, I will cover other material in my lectures. **You will be responsible for knowing this material too!**
-   A large body of well-designed research has demonstrated the detrimental effects of laptops on learning in a lecture/discussion based environment. Please be courteous and do not use your computers for anything other than class related work (taking notes and so on). Cellular phones are not to be used during class time!
-   Letters of recommendation. If you are a hard working student and serious about a career in public service, I will be a dedicated advocate for you on the job market and will happily write letters of recommendation on your behalf. There is, however, one condition and one recommendation. The condition: I will not write a letter of recommendation for your while you are in my class. This is because to write a good faith, sincere, and thoughtful recommendation, I will need to be able to consider your work as a whole, and while the class is on-going, my assessment of you will be incomplete. After the semester is over, I am happy to help in any way I can, including writing letters. The recommendation: Make an appointment to visit my office hours at least once over the course of the semester to talk informally about your goals, career interests, and other professional ambitions so I can get a better sense of who you are as individuals. The better I know you, the more effective I can be at writing letters on your behalf and thinking of you when opportunities arise.
-   Attend class! Again, class participation is 10% of your grade, and you can't participate if you're not in class. If you DO need to miss class (emergencies, sickness, etc.), please contact me as soon as possible and let me know. It will be your responsibility to notify me and to get any notes/materials from other students.
-   Cell phones: we all have them, and they can be quite distracting. I ask that you please be courteous and silence your cell phone and leave it out of sight (in a pocket/purse/bag) during class.
-   Feel free to eat and drink in class. I only ask that you do so quietly and in a manner that does not disrupt class.
-   All assignments and non-textbook readings will be posted to the class Zotero Library. I will email any announcements or updates to the class and also post them in the Blackboard. Report any trouble accessing anything on the Blackboard as soon as you encounter the problem.
-   I have a strict open door policy. If there is anything about the course, the assignments, the grading, the material, class, or anything related to public administration/policy or statistics broadly that you would like to discuss, do not hesitate to visit me during office hours or email me. I can respond via email, schedule a phone call, or schedule a separate meeting. I am here to help, so please do not hesitate to reach out to me. (But please be respectful of my time!)
-   **HAVE FUN!** Public administration/policy is a broad topic that explores big, important questions that affect everyone. Discussing these topics should be as fun and interesting as it is challenging.
-   The table below lays out the grading scale that will be used in assigning final course grades.
-   Students with special physical and/or learning needs will be accommodated. Please notify the Disabilities Office and me as soon as possible so that reasonable accommodations can be made.

::: callout-important
**NOTE:** Throughout the semester, I may add or subtract readings as needed to adjust the course according to your progress, engagement, and interests.
:::

Table. Grade Scale Used for Calculating Class Grades

| Percent | Grade | Points |
|:-------:|:-----:|:------:|
| 93-100  |   A   |  4.0   |
|  90-92  |  A-   |  3.7   |
|  87-89  |  B+   |  3.3   |
|  83-86  |   B   |  3.0   |
|  80-82  |  B-   |  2.7   |
|  77-79  |  C+   |  2.3   |
|  73-76  |   C   |  2.0   |
|  70-72  |  C-   |  1.7   |
|  67-69  |  D+   |  1.3   |
|  63-66  |   D   |  1.0   |
|  60-62  |  D-   |  0.7   |
|  \< 60  |   F   |  0.0   |

::: callout-note
**Note:** the percent refers to the percent of available weighted points earned. Each assignment is weighted by the proportion of the final grade made up by the assignment itself, as described above.
:::

### Academic integrity

Academic honesty is something your professor takes very seriously. Cheating in any form will not be tolerated. Students are required to be familiar with the university's academic honesty policies; ignorance is not an excuse for dishonest behavior. In all cases of cheating, a Violation of Academic Integrity Report will be submitted to the Dean of Graduate Studies to be placed in your university file, with copies provided to you, the department head, and the Dean of Rockefeller College. Additional penalties may include some combination of the following: revision and re-submission of the assignment, reduction of the grade or failure of the assignment, reduction of the course grade or failure of the course, filing of a case with the Office of Conflict Resolution and Civic Responsibility, suspension, or expulsion. For a more detailed description of the university's academic honesty policies, visit the [site](http://www.albany.edu/graduatebulletin/requirements_degree.htm#standards_integrity).

### Students with Disabilities

We are committed to providing an accessible learning environment for all students. This includes students with physical, sensory, medical, cognitive, learning, mental health, and other disabilities. If you have, or think you may have a disability, please contact Disability Access and Inclusion Student Services (DAISS) by emailing daiss\@albany.edu or calling 518 -442-5501. DAISS staff will explain the documentation and registration process, and set you up with an appointment. Once you have completed registration, you will be provided with a letter to inform your instructors that you are a student with a disability registered with DAISS, and which lists the recommended reasonable accommodations for your courses.

### Counseling Center

The Counseling Center (518-442-5800; 400 Patroon Creek Blvd, Suite 104) offers counseling and consultations regarding personal concerns, self-help information, and connections to off-campus resources. More information can be found at their [site](http://www.albany.edu/counseling_center/index.shtml).

### Library Assistance

SUNY-Albany offers a great collection available in several different media. Access to research help and library tutorials can be found online at the [library's site](http://library.albany.edu/).

For information about SUNY-Albany's Dewey Graduate Library, which is located on the Downtown Campus, visit their [site](http://library.albany.edu/dewey?source=drop).

### Writing Center

The university offers a number of services for students who need assistance with writing and research projects. Support is available in the Writing Center (518-442-4061; 140 HU) and at the University Library. Information about the Writing Center can be found at their [site](http://www.albany.edu/writing/index.html).

### Title IX and Sexual Violence Prevention

Title IX of the Education Amendments of 1972 is a federal civil rights law that prohibits discrimination on the basis of sex in federally funded education programs and activities. The SUNY-wide Sexual Violence Prevention and Response Policies prohibit offenses defined as sexual harassment, sexual assault, intimate partner violence (dating or domestic violence), sexual exploitation, and stalking. The SUNY-wide Sexual Violence Prevention and Response Policies apply to the entire University at Albany community, including students, faculty, and staff of all gender identities. The University at Albany provides a variety of resources for support and advocacy to assist individuals who have experienced sexual offenses.

Confidential support and guidance can be found through the Counseling Center (518-442-5800, [or online](https://www.albany.edu/counseling_center/)), the University Health Center (518-442-5454, [or online](https://www.albany.edu/health_center/)), and the Interfaith Center (518-489-8573, [or online](https://www.albany.edu/spirituality/onCampus.shtml)). Individuals at these locations will not report crimes to law enforcement or university officials without permission, except for in extreme circumstances, such as a health and/or safety emergency. Additionally, the Advocates at the University at Albany's Advocacy Center for Sexual Violence are available to assist students without sharing information that could identify them (518-442-CARE, [or online](https://www.albany.edu/advocacycenter/)).

Sexual offenses can be reported non-confidentially to the Title IX Coordinator within The Office for Equity and Compliance (518-442-3800, [or online](https://www.albany.edu/equity-compliance/), Building 25, Room 117) and/or the University Police Department (518-442-3131, [or online](http://police.albany.edu/)).

::: callout-important
**PLEASE NOTE:** Faculty members are considered "responsible employees" at the University at Albany, meaning that they are required to report all known relevant details about a complaint of sexual violence to the University's Title IX Coordinator, including names of anyone involved or present, date, time, and location.
:::

In case of an emergency, please call 911.

### Incomplete Grade Policy

A tentative grade given only when the student has nearly completed the course but due to circumstances beyond the student's control the work is not completed on schedule. The date for the completion of the work is specified by the instructor. The date stipulated will not be later than one month before the end of the session following that in which the Incomplete is received. The grade I is automatically changed to E or U unless work is completed as agreed between the student and the instructor.

### Absence due to religious observance

Students are excused, without penalty, to be absent because of religious beliefs, and will be provided equivalent opportunities for make-up examinations, study, or work requirements missed because of such absences. Students should notify the instructor of record in a timely manner, and the instructor will work directly with students to accommodate religious observances. Online courses will not schedule any assignment deadlines on religious holidays.
